# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ACRNAME: openhackx6e34ru4acr

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
    
      - name: Push image to container registry
        run: az acr build --image "devopsoh/api-userprofile:${{ github.sha }}" --registry ${{ env.ACRNAME }} .